title: SeungHyeon Jo (Jo,SH)
logo: /assets/img/logo.jpeg
email: coolwind@outlook.kr
description: Senior Systems Architect | Physical AI Deployment & Safety-critical Systems
favicon: true
google_analytics: G-5VQG4FFG1Q
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/coolwindjo
  - name: Blog
    icon: <i class="fa-solid fa-blog"></i>
    link: https://coolwindjo.github.io
  - name: LinkedIn
    icon: <i class="fa-brands fa-linkedin"></i>
    link: https://linkedin.com/in/josh-auto

navigation:
  - name: ABOUT ME
    link: ./index.html#about-me
  - name: EDUCATION
    link: ./index.html#education
  - name: SKILLS
    link: ./index.html#skills
  - name: WORK EXPERIENCE
    link: ./index.html#work-experience
  - name: PUBLICATIONS
    link: ./index.html#publications
  - name: LANGUAGE
    link: ./index.html#language
  - name: AWARDS
    link: ./index.html#awards
  - name: PATENTS
    link: ./index.html#patents
  - name: GLOSSARY OF TECHNICAL TERMS
    link: ./index.html#glossary-of-technical-terms